# Generated by Django 4.0.2 on 2022-02-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hotel_name', models.CharField(max_length=200)),
                ('Hotel_price', models.IntegerField()),
                ('Hotel_rating', models.IntegerField()),
                ('Hotel_location', models.CharField(max_length=500)),
            ],
        ),
    ]
